import Head from "next/head"

import Header from "../components/Header"
import Body from "../components/Body"
import Footer from "../components/Footer"

import MyColeccion from "../components/elements/MyColeccion"

const Coleccion = () => {
    return (
        <div className="flex flex-col h-screen justify-between">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Body>
                <MyColeccion />
            </Body>
            <Footer />
        </div>
    )
}

export default Coleccion
