import Head from "next/head"
import Header from "../components/Header"
import Body from "../components/Body"
import Footer from "../components/Footer"

import Inicio from "../components/elements/Inicio"
import Guia from "../components/elements/Guia"
import Colaboraciones from "../components/elements/Colaboraciones"

export default function Home() {
    return (
        <div className="flex flex-col h-screen justify-between">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Body>
                <Inicio />
                <Guia />
                <Colaboraciones />
            </Body>
            <Footer />
        </div>
    )
}
